using e_systemApplicationAPI.Data;
using MailKit.Security;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using MimeKit.Text;
using Org.BouncyCastle.Asn1.Ocsp;
using MailKit.Net.Smtp;

namespace e_systemApplicationAPI.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class EmailsController : ControllerBase
    {
        private readonly IConfiguration _config;
        private readonly ApplicationDbContext _context;

        public EmailsController(IConfiguration config, ApplicationDbContext context)
        {
            _config = config;
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> SendApprovalEmail ([FromBody] int systemOwnerId)
        {
            var emailOwners = _context.SystemOwners.Where(s=>s.SystemId == systemOwnerId && s.IsActive == true).Select(s=>s.Email).ToList();
            var email = new MimeMessage();
            if(emailOwners != null)
            {
                email.From.Add(MailboxAddress.Parse("e-systemApplication@lgm.gov.my"));
                foreach (var owner in emailOwners)
                {
                    email.To.Add(MailboxAddress.Parse(owner));
                }
                email.Subject = "New user request for application";
                string htmlMessageRegister = GenerateHtmlApproval();
                email.Body = new TextPart(TextFormat.Html) { Text = htmlMessageRegister };
            }

            using (var client = new SmtpClient())
            {
                client.LocalDomain = "lgm.gov.my";
                await client.ConnectAsync(_config.GetSection("EmailHost").Value, 25, SecureSocketOptions.None).ConfigureAwait(false);
                await client.SendAsync(email).ConfigureAwait(false);
                await client.DisconnectAsync(true).ConfigureAwait(false);
            }

            return Ok(new { message = "Email successfully send" });
        }

        [HttpPost]
        public async Task<IActionResult> SendAssignEmail(int systemId)
        {
            var email = new MimeMessage();
            email.From.Add(MailboxAddress.Parse("e-systemApplication@lgm.gov.my"));
            email.To.Add(MailboxAddress.Parse("sabariah@lgm.gov.my"));
            email.To.Add(MailboxAddress.Parse("SHAZWANI@LGM.GOV.MY"));
            email.Subject = "New user request for assign application";
            string htmlMessageRegister = GenerateHtmlAssign();
            email.Body = new TextPart(TextFormat.Html) { Text = htmlMessageRegister };

            using (var client = new SmtpClient())
            {
                client.LocalDomain = "lgm.gov.my";
                await client.ConnectAsync(_config.GetSection("EmailHost").Value, 25, SecureSocketOptions.None).ConfigureAwait(false);
                await client.SendAsync(email).ConfigureAwait(false);
                await client.DisconnectAsync(true).ConfigureAwait(false);
            }

            return Ok(new { message = "Email successfully send" });
        }


        private string GenerateHtmlApproval()
        {
            string htmlMessage = "<html>" +
                "<body>" +
                "<h2>Assalamualaikum wbt & Greetings,</h2>" +
                "<p>To whom it may concern,  <br/><br/>" +
                "<p><b><u>NOTICE NEW USER REQUEST FOR APPLICATION</u></b><br/><br/>" +
                "2. We kindly request the cooperation of system owner to approve requested application in e-systemApplication.<br /><br />" +
                "Thank you,<br/>" +
                "<b>e-SystemApplication</b></p>" +
                "<i>Attention, this message is automatically generated by the system. <i>" +
                "</body>" +
                "</html>";
            return htmlMessage;
        }

        private string GenerateHtmlAssign()
        {
            string htmlMessage = "<html>" +
                "<body>" +
                "<h2>Assalamualaikum wbt & Greetings,</h2>" +
                "<p>To whom it may concern,  <br/><br/>" +
                "<p><b><u>NOTICE NEW USER REQUEST FOR ASSIGN APPLICATION</u></b><br/><br/>" +
                "2. We kindly request the cooperation of system admin to approve requested application in e-systemApplication.<br /><br />" +
                "Thank you,<br/>" +
                "<b>e-SystemApplication</b></p>" +
                "<i>Attention, this message is automatically generated by the system. <i>" +
                "</body>" +
                "</html>";
            return htmlMessage;
        }

    }
}
