using e_systemApplicationAPI.Data;
using e_systemApplicationAPI.Models;
using MailKit.Net.Smtp;
using MailKit.Security;
using MimeKit;
using MimeKit.Text;

namespace e_systemApplicationAPI.Repository
{
    public class EmailRepository
    {
        private readonly IConfiguration _config;
        private readonly ApplicationDbContext _context;


        public EmailRepository(IConfiguration config, ApplicationDbContext dbContext)
        {
            _config = config;
            _context = dbContext;
        }
        public async Task<Application> sendWelcomeEmail(Application application)
       {
           var email = new MimeMessage();
           email.From.Add(MailboxAddress.Parse("e-systemApplication@lgm.gov.my"));
           email.To.Add(MailboxAddress.Parse(application.UserEmail));
           email.Subject = "New application permission have been assigned";
           string htmlMessageRegister = GenerateHtmlAssign(application);
           email.Body = new TextPart(TextFormat.Html) { Text = htmlMessageRegister };

           using (var client = new SmtpClient())
           {
               client.LocalDomain = "lgm.gov.my";
               await client.ConnectAsync(_config.GetSection("EmailHost").Value, 25, SecureSocketOptions.None).ConfigureAwait(false);
               await client.SendAsync(email).ConfigureAwait(false);
               await client.DisconnectAsync(true).ConfigureAwait(false);
           }

            return application;
       }


        private string GenerateHtmlAssign(Application application)
        {
            var system = _context.Systems
                .Where(x => x.Id == application.SystemId)
                .Select(x => x.SystemName)
                .FirstOrDefault();

            string htmlMessage = "<html>" +
                "<body>" +
                "<h2>Assalamualaikum wbt & Greetings,</h2>" +
                "<p>To whom it may concern,</p>" +
                "<p><b><u>NOTICE APPLICATION HAVE BEEN ASSIGNED</u></b></p>" +
                "<p>2. Requested application have been approved and assigned in e-systemApplication. Please login to: " + system + "<br /><br />" +
                "Thank you,<br />" +
                "<b>e-SystemApplication</b></p>" +
                "<p><i>Attention, this message is automatically generated by the system.</i></p>" +
                "</body>" +
                "</html>";

            return htmlMessage;
        }
    }
}
